### ISSUE TITLE
add help text on entering and exiting a battle

### ISSUE THREAD

**Issue by pepem00n** [pepemon-dao/pepemon-degen-battleground#56]
users must know that they have to execute the metamask transactions to proceed with the battle, that's why it will be good to add a help text while in the matchmaking screen depending on the situation

trying to enter a battle 
<img width="1334" alt="Screenshot 2023-03-11 at 15 49 13" src="https://user-images.githubusercontent.com/72664737/224491377-495bbaa5-d7c7-4302-bd86-33be93955efa.png">

- user should see a help text on the screen "Successfully confirm the transactions in your wallet to resolve the battle on blockchain"

trying to exit a matchmaking
<img width="1163" alt="Screenshot 2023-03-11 at 15 55 10" src="https://user-images.githubusercontent.com/72664737/224491426-a38fc795-77b3-4ad4-b522-f7b52e97f3c3.png">

- user should be indicated with a help text "You are currently waiting for an opponent. If you want to leave the matchmaking you need to execute successfully the blockchain transaction, otherwise you will be the next in queue for battle."

**Comment by pepem00n** [comment]
although i've seen it present, i still think it's quite buggy and no following the suggestions above @benzo-diazepine

**Comment by benzo-diazepine** [comment]
> although i've seen it present, i still think it's quite buggy and not following the suggestions above
> 
> can we get a feature branch with this and work on it soon @benzo-diazepine

sure, I think its just the text component glitching when the screen size changes

**Comment by benzo-diazepine** [comment]
#91 should fix this
