### ISSUE TITLE
listen for the status of the transaction and return user to matchmaking screen if failed

### ISSUE THREAD

**Issue by alex0xhodler** [pepemon-dao/pepemon-degen-battleground#69]
current behavior: if the transaction status is failed, user will be stuck in matchmaking screen with Exit button disabled, only way to restart is to refresh the browser tab.

desired behavior: if the transaction status is failed, return user to 'search for an opponent' screen the same way the game behaves when transaction is rejected from metamask.

**Comment by benzo-diazepine** [comment]
#75 should fix this
